# Site settings
title: João Batista Personal Website
description: A website about me and my interests.
url: https://joaobf.github.io

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

# Navigation
nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Blog: _posts

# Author information
author:
  name: João Batista Fernandes
  email: joaofernandes.engcomp@gmail.com
  bio: A software engineer and outdoor enthusiast.

# Social media links
social:
  - title: GitHub
    url: https://github.com/jotabf/
  - title: LinkedIn
    url: https://www.linkedin.com/in/jo%C3%A3o-batista-fernandes-bb134350/
